# Vamos a tomar la imagen de node versión 16 como base
FROM node:16.14.0

# Debemos de establecer el directorio de trabajo
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install

EXPOSE 3000

#CMD [ "npm" ,"run start:dev"]
# Y listo, ejecutamos la aplicación.
ENTRYPOINT npm run start:dev